<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Input\" />
    <Folder Include="Helpers\" />
    <Folder Include="Output\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoinsApp.BLL\CoinsApp.BLL.csproj" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CoinsApp.DB\CoinsApp.DB.sqlproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
			<OutputItemType>None</OutputItemType>
		</ProjectReference>
	</ItemGroup>

	<Target Name="CopyDatabaseDacpac"
        AfterTargets="Build">

		<ItemGroup>
			<DatabaseDacpac Include="$(MSBuildProjectDirectory)\..\CoinsApp.DB\bin\$(Configuration)\CoinsApp.DB.dacpac" />
		</ItemGroup>

		<Copy
		  SourceFiles="@(DatabaseDacpac)"
		  DestinationFolder="$(TargetDir)Database"
		  SkipUnchangedFiles="true" />
	</Target>

</Project>
